### ISSUE TITLE
동일 포스팅이 계속 전달되는 현상

### ISSUE THREAD

**Issue by yenarue** [BenjaminKim/awesome-blogs#13]
안녕하세요. 

제공해주신 dev RSS 를 Slack에 연결하여 사용하려 합니다!
어제 연결해두고 아침에 확인해보니 아래와 같이 동일 포스팅이 계속 전달되고 있더라구요ㅠㅠ
버그인 것인지 원래 컨셉인건지 궁금합니다.
후자라면 dev, company, insight 모두 동일 컨셉인지요?

확인 부탁드리겠습니다.
감사합니다 :-)

![screenshot from 2018-07-28 11-32-35](https://user-images.githubusercontent.com/11554946/43352150-2f79d3e8-925a-11e8-933b-959286abbf83.png)
![screenshot from 2018-07-28 11-32-55](https://user-images.githubusercontent.com/11554946/43352151-2fa756ba-925a-11e8-8f61-cc004d6a7b71.png)
![screenshot from 2018-07-28 11-33-23](https://user-images.githubusercontent.com/11554946/43352152-2fd4629a-925a-11e8-8b8a-daf641422c5a.png)
![screenshot from 2018-07-28 11-33-42](https://user-images.githubusercontent.com/11554946/43352153-300018fe-925a-11e8-90da-2437d4e175fb.png)
![screenshot from 2018-07-28 11-33-55](https://user-images.githubusercontent.com/11554946/43352154-302e7280-925a-11e8-92b9-907eab4656b3.png)

**Comment by BenjaminKim** [comment]
혹시 이 포스팅이 아직도 중복으로 나오시나요?
제 생각에는 이 `웹 아키텍쳐 입문` 을 포스팅하신 분이 7월 28일 오전 9시로 예약 발행을 해서 문제가 되지 않았을까 싶은데요. (예약한 시간이 아직 안되었지만 awesome-blogs 에는 미리 들어와버림)

제가 서버 쪽에서 처리가 가능할 것 같기도 합니다. 한 번 고쳐볼께요.

**Comment by BenjaminKim** [comment]
abb0bd4a9678ea00b0e655f8bfd5dedf85603ea7

처리해 놓았습니다. (테스트는 못해보았지만 잘되지 않을까 싶습니다 ^^;)
