### ISSUE TITLE
readme 바로가기 오류

### ISSUE THREAD

**Issue by AndersonChoi** [BenjaminKim/awesome-blogs#15]
Aloha~! 반갑습니다.
readme에 있는 android application 다운로드 url경로가 잘못되어있습니다~

**Comment by BenjaminKim** [comment]
@AndersonChoi 2년만의 댓글 죄송합니다!
안드로이드 앱은 현재 내려가버려서 링크를 삭제했습니다. 다시 개발될지는....... 😢
