### ISSUE TITLE
Entry, link 필드의 url이 상대 경로로 내려주는 경우가 있습니다.

### ISSUE THREAD

**Issue by jungilhan** [BenjaminKim/awesome-blogs#6]
현재 확인한 블로그는 다음과 같습니다. (타이틀 ・ 작성자 ・링크)
 * 도도 테이블 101 ・ 강효준 ・ /2017/02/17/dodotable.html
 * 스포카 한 산스 웹폰트로 사용하기 ・ 강영화, /2017/02/15/using-shs-as-webfonts.html
 * 스포카 한 산스2.0에 관한 몇 가지 ・ 김동휘 ・ /2017/02/15/SHS-trivia.html
 * flake8-import-order-spoqa ・ 홍민희 ・ /2017/02/12/flake8-import-order-spoqa.html

연관 이슈
 * https://github.com/jungilhan/awesome-blogs-android/issues/8

**Comment by BenjaminKim** [comment]
👌

**Comment by BenjaminKim** [comment]
@jungilhan 수정했습니다!
